routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;


Route::get('/login', [Admin\Auth\LoginController::class, 'index'])
		->name('login.index');
Route::post('/login', [Admin\Auth\LoginController::class, 'login'])
		->name('login');
Route::get('/resend-verifyemail/{email}', [Admin\Auth\LoginController::class, 'resendVerifyEmail'])
		->name('resend-verifyemail');

Route::get('/password/email', [Admin\Auth\ForgotPasswordController::class, 'index'])
		->name('password.email.index');
Route::post('/password/email/send', [Admin\Auth\ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email.send');

Route::get('/password/reset/{token}', [Admin\Auth\ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('/password/reset', [Admin\Auth\ResetPasswordController::class, 'reset'])->name('password.reset.update');


Route::group(['middleware' => 'admin'], static function() {
	Route::get('/', function() {
		return redirect()->route('admin.dashboard.index');
	});
	
	Route::post('/logout', [Admin\Auth\LoginController::class, 'logout'])
		->name('logout');

	Route::get('/dashboard', [Admin\DashboardController::class, 'index'])
			->name('dashboard.index');

	Route::resource('/banner', Admin\BannerController::class)->except('show');
	Route::get('/data/banner', Admin\DataTable\BannerController::class)
			->name('banner.data');

	Route::resource('/category', Admin\CategoryController::class)->except('show');
	Route::get('/data/category', Admin\DataTable\CategoryController::class)
			->name('category.data');

	Route::resource('/comments', Admin\CommentController::class)->except('show', 'index');
	Route::delete('/comments/{id}/delete-reply', [Admin\CommentController::class, 'destroyReply'])
			->name('comments.destroyReply');
	Route::get('/data/comments', Admin\DataTable\CommentController::class)
			->name('comments.data');

	Route::get('/video/from-channel', [Admin\VideoController::class, 'createFromChannel'])
			->name('video.from-channel');
	Route::get('/video/video-from-channel', [Admin\VideoController::class, 'videoFromChannelIndex'])
			->name('video.video-from-channel.index');
	Route::post('/video/video-from-channel-check', [Admin\VideoController::class, 'videoFromChannel'])
			->name('video.video-from-channel');
	Route::post('/video/more-video-from-channel/', [Admin\VideoController::class, 'moreVideoFromChannel'])
			->name('video.more-video-from-channel');
	Route::post('/video/store-video-from-channel', [Admin\VideoController::class, 'storeVideoFromChannel'])
			->name('video.store-video-from-channel');

	Route::post('/video/search-video-from-channel', [Admin\VideoController::class, 'searchVideoFromChannel'])
			->name('video.search.video-from-channel');
	Route::get('/video/search-video-from-channel', [Admin\VideoController::class, 'searchVideoFromChannelIndex'])
			->name('video.search.video-from-channel.index');
	Route::post('/video/search-more-video-from-channel/', [Admin\VideoController::class, 'searchMoreVideoFromChannel'])
			->name('video.search.more-video-from-channel');
	// Route::post('/video/search-store-video-from-channel', [Admin\VideoController::class, 'searchStoreVideoFromChannel'])
	// 		->name('video.search.store-video-from-channel');


	Route::resource('/video', Admin\VideoController::class);
	Route::get('/data/video', Admin\DataTable\VideoController::class)
			->name('video.data');

	Route::resource('/playlist', Admin\PlaylistController::class);
	Route::get('/data/playlist', Admin\DataTable\PlaylistController::class)
			->name('playlist.data');

	Route::resource('/channel', Admin\ChannelController::class)->except('show');
	Route::get('/data/channel', Admin\DataTable\ChannelController::class)
			->name('channel.data');

	Route::resource('/users', Admin\UserController::class);
	Route::get('/data/users', Admin\DataTable\UserController::class)
			->name('users.data');

	Route::get('/profile', [Admin\ProfilController::class, 'index'])
			->name('profil.index');
	Route::get('/profile/edit', [Admin\ProfilController::class, 'edit'])
			->name('profil.edit');
	Route::put('/profile/{id}/update', [Admin\ProfilController::class, 'update'])
			->name('profil.update');
	Route::put('/profile/{id}/change-password', [Admin\ProfilController::class, 'changePassword'])
			->name('profil.changePassword');

	Route::resource('/admins', Admin\AdminController::class);
	Route::get('/data/admins', Admin\DataTable\AdminController::class)
			->name('admins.data'); 
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;
use App\Http\Controllers\Customer;
use App\Http\Controllers\StorageController;

Route::get('/', [Controllers\WelcomeController::class, 'index'])->name('welcome');
Route::get('/login', [Controllers\Auth\LoginController::class, 'index'])->name('login');
Route::post('/login', [Controllers\Auth\LoginController::class, 'login']);
Route::post('/resend-verifyemail', [Controllers\Auth\LoginController::class, 'resendVerifyEmail']);

Route::get('/register', [Controllers\Auth\RegisterController::class, 'index'])->name('register');
Route::post('/register', [Controllers\Auth\RegisterController::class, 'store']);
Route::get('/email/confirmation/{email}', [Controllers\Auth\RegisterController::class, 'confirmEmail'])->name('confirm.email');

Route::get('/home', [Controllers\HomeController::class, 'index'])->name('home');

Route::get('/password/reset', [Controllers\Auth\ForgotPasswordController::class, 'showLinkRequestForm']);
Route::post('/password/email', [Controllers\Auth\ForgotPasswordController::class, 'postEmail']);

Route::get('/password/reset/{token}', [Controllers\Auth\ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('/password/reset', [Controllers\Auth\ResetPasswordController::class, 'reset']);

Route::get('/authorize/{social}', [Controllers\Auth\SocialAuthorizeController::class, 'redirectToProvider']);
Route::get('/authorize/{social}/callback', [Controllers\Auth\SocialAuthorizeController::class, 'handleProviderCallback']);

Route::resource('/category', Controllers\CategoryController::class)->only('index', 'show');
Route::get('/api/category', [Controllers\CategoryController::class, 'APIIndex']);


Route::group(['prefix' => 'customer'], static function () {
    Route::group(['middleware' => 'auth'], static function() {
        Route::post('/logout', [Controllers\Auth\LoginController::class, 'logout'])->name('logout');
        Route::get('/', [Customer\MyAccountController::class, 'index'])->name('customer.account');
        Route::get('/password', [Customer\PasswordController::class, 'index'])->name('customer.password');
        Route::post('/password', [Customer\PasswordController::class, 'store']);

        Route::get('/api/avatar', [Customer\AvatarController::class, 'APIAvatar']);
        Route::post('/avatar', [Customer\AvatarController::class, 'store']);

        Route::get('/video', [Customer\VideoController::class, 'index'])->name('customer.video');
        Route::get('/video/watch/{video:slug}', [Customer\VideoController::class, 'watch'])->name('customer.video.watch');
        Route::get('/video/{video:slug}', [Customer\VideoController::class, 'edit'])->name('customer.video.edit');
        Route::put('/video/{video:slug}/update', [Customer\VideoController::class, 'update'])->name('customer.video.update');
        Route::delete('/video/{video:id}/delete', [Customer\VideoController::class, 'destroy']);
        Route::post('/video', [Customer\VideoController::class, 'store']);

        Route::get('/channel', [Customer\ChannelController::class, 'index'])->name('customer.index.channel');
        Route::get('/channel/create', [Customer\ChannelController::class, 'create'])->name('customer.create.channel');
        Route::post('/channel', [Customer\ChannelController::class, 'store']);
        Route::get('/channel/{channel}/edit', [Customer\ChannelController::class, 'edit'])->name('customer.edit.channel');
        Route::put('/channel/{channel}/update', [Customer\ChannelController::class, 'update'])->name('customer.update.channel');

        Route::post('/like', [Customer\UserLikeVideoController::class, 'store']);
        Route::post('/comment', [Customer\UserVideoCommentController::class, 'storeNewComment']);
        Route::post('/comment/reply', [Customer\UserVideoCommentController::class, 'storeReplyComment']);
        Route::post('/like-comment', [Customer\UserVideoCommentController::class, 'storeResponsComment']);
        Route::post('/subscribe', [Customer\UserSubscribeController::class, 'store']);

        Route::get('/playlist', [Customer\UserPlaylistController::class, 'index'])->name('customer.playlist');
        Route::get('/api/playlist', [Customer\UserPlaylistController::class, 'APIIndex']);
        Route::post('/playlist', [Customer\UserPlaylistController::class, 'store']);
        Route::post('/playlist-video', [Customer\UserPlaylistController::class, 'storeVideoPlaylist']);
        Route::delete('/playlist/{playlist}/{video}/delete', [Customer\UserPlaylistController::class, 'destroy']);

        Route::get('/notifications', [Customer\UserNotificationController::class, 'getUnreadNotification']);
        Route::get('/notifications/mark-read-all', [Customer\UserNotificationController::class, 'markReadAllNotif']);
        Route::get('/notifications/{id}', [Customer\UserNotificationController::class, 'markReadNotif']);
        
    });
    
});


Route::get('/watch/{channel}/{video}', Controllers\VideoController::class)->name('video');
Route::get('/watch/{channel}', Controllers\ChannelController::class)->name('channel');
Route::get('/api/video/{video}', [Controllers\VideoCommentController::class, 'APIIndex']);
Route::post('/api/search/video', [Controllers\ChannelController::class, 'search']);


Route::get('/search', [Controllers\SearchController::class, 'index'])->name('search.index');
Route::get('/banner/{slug}', [Controllers\BannerController::class, 'show'])->name('banner.show');


Route::get('/retrieve-storage/{encryptedPath}', [StorageController::class, 'retrieve'])->name('storage.retrieve');

Route::get('/about', [Controllers\Footer\AboutController::class, 'index'])->name('footer.about.index');
Route::get('/about-use', [Controllers\Footer\AboutUsController::class, 'index'])->name('footer.about-use.index');
Route::get('/media-sosial', [Controllers\Footer\MediaSosialController::class, 'index'])->name('footer.media-sosial.index');
Route::get('/pusat-bantuan', [Controllers\Footer\PusatBantuanController::class, 'index'])->name('footer.pusat-bantuan.index');

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Video extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function getImage()
    {
        if ($this->video_type === 'upload') {
            return route('storage.retrieve', encrypt($this->thumbnail));
            
        } else {
            return $this->thumbnail;
        }
    }

    public function getVideo()
    {
        if ($this->video_type === 'upload') {
            return route('storage.retrieve', encrypt($this->path));

        } else {
            return $this->path;
        }
    }

    public function countLike()
    {
        return $this->userLikeVideos()->where('like', 'like')->get()->count();
    }

    public function countDislike()
    {
         return $this->userLikeVideos()->where('like', 'dislike')->get()->count();
    }

    public function countSubscribe()
    {
         return $this->createBy->channel->userSubscribes()->get()->count();
    }

    public function createBy()
    {
    	return $this->belongsTo(User::class, 'created_by', 'id');
    }

    public function userLikeVideos()
    {
        return $this->hasMany(UserLikeVideo::class);
    }

    public function tagVideos()
    {
        return $this->hasMany(TagVideo::class);
    }

    public function videoComments()
    {
        return $this->hasMany(Comment::class);
    }

    public function videoCommentParents()
    {
        return $this->videoComments()->whereNull('parent_id');
    } 

    public function playlists()
    {
        return $this->hasMany(Playlist::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
    
}

app/Http/Controllers/Admin/DataTable/VideoController.php
<?php

namespace App\Http\Controllers\Admin\DataTable;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Video;

class VideoController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $videos = Video::orderBy('created_at', 'asc');

        return datatables()->of($videos)
                        ->editColumn('thumbnail', 'layouts.admin.DT-button.DT-video-image')
                        ->addColumn('action', 'layouts.admin.DT-button.DT-video-action')
                        ->rawColumns(['action', 'thumbnail'])
                        ->addIndexColumn()
                        ->toJson();
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\{Channel, Video};
use Inertia\Inertia;
use Auth, DB, Image, Storage, Str;
use App\Http\Resources\VideoResource;

class VideoController extends Controller
{
    public function __invoke(Request $request)
    {
        $channel = Channel::with('user.videos')->where('links', $request->channel)->firstOrFail();
        $video = $channel->user->videos()->where('slug', $request->video)->firstOrFail();

        $video->views_count = $video->views_count + 1;
        $video->save();
        
        $other_videos = $channel->user->videos()->where('slug', '!=', $request->video)->limit(8)->get();

        return Inertia::render('ShowVideo', [
            'channel' => $channel,
            'video' => new VideoResource($video),
            'other_videos' => VideoResource::collection($other_videos)
        ]);    
    }
}

resources/views/admin/video/create.blade.php
@extends('layouts.admin.default')

@section('title', 'Create Video')
@section('pageTitle', 'Create Video')

@section('content')

<div class="card card-custom gutter-b example example-compact">
	<div class="card-header">
		<h3 class="card-title">Create a New Video</h3>
	</div>

	<form 
		action="{{ route('admin.video.store') }}" 
		method="POST"
		enctype="multipart/form-data">

		@csrf

		<div class="card-body">
			<div class="form-group">
				<label>Video For 
				<span class="text-danger">*</span></label>
				<select 
					name="video_for"
					class="form-control select2 @error('video_for') is-invalid @enderror"
					id="videoFor">
					@foreach($users as $user)
						<option></option>
			      		<option 
			      			value="{{ $user->id }}"
			      			@if(collect(old('video_for'))->contains($user->id))
			      				selected="selected" 
			      			@endif
			      		>
			      		{{ $user->name }}
			      	</option>
			      	@endforeach
			     </select>
				@error('video_for')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>

			<div class="form-group">
							
				<label for="">Video Category</label>
				<select name="categories[]" id="categories" class="form-control select2 @error('categories') is-invalid @enderror" multiple="">
					@foreach($categories as $category)
						<option 
							value="{{ $category->id }}"  
							@if(collect(old('categories'))->contains($category->id))  
								selected="selected" 
							@endif
						>
							{{ $category->name }}
						</option>
					@endforeach
				</select>

				@error('categories')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>

			<div class="form-group">
				<label>Type Video
				<span class="text-danger">*</span></label>
				<select 
					name="video_type"
					class="form-control @error('video_type') is-invalid @enderror" 
					id="videoType">
					<option 
						id="pilih" 
						value="">
						--Pilih Type video--
					</option>
					<option 
						id="youtube" 
						value="youtube" 
						@if (old('video_type') == "youtube") {{ 'selected' }} @endif>
						Youtube
					</option>
					<option 
						id="upload" 
						value="upload" 
						@if (old('video_type') == "upload") {{ 'selected' }} @endif>
						Upload
					</option>
			     </select>
				@error('video_type')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div 
				class="form-group"
				id="showYoutube">
				<label>URL Video 
				<span class="text-danger">*</span></label>
				<input 
					type="text"
					name="pathYoutube"
					id="pathYoutube" 
					class="form-control @error('pathYoutube') is-invalid @enderror"
					value="{{old('path')}}" 
					placeholder="Enter a new user. " />
				<span class="form-text text-muted">
					Import videos from YouTube, copy / Paste your video link here.
				</span>
				@error('pathYoutube')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>

			<div 
				class="form-group"
				id="showTitle">
				<label>Title 
				<span class="text-danger">*</span></label>
				<input 
					type="text"
					name="title"
					id="title" 
					class="form-control @error('title') is-invalid @enderror"
					value="{{old('title')}}" 
					placeholder="Enter a new user. " />
				@error('title')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div 
				class="form-group"
				id="showUpload">
				<label>
					File Video
					<span class="text-danger">*</span>
				</label>
				<input 
					type="file"
					name="pathUpload"
					id="pathUpload" 
					class="form-control @error('pathUpload') is-invalid @enderror" 
					placeholder="Enter a new avatar." />
				<span class="form-text text-muted">
					Select video files to upload, select your video files.
				</span>
				@error('pathUpload')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>

			<div 
				class="form-group"
				id="showThumbnail">
				<label>Thumbnail
				<input 
					type="file"
					name="thumbnail"
					id="thumbnail" 
					class="form-control @error('thumbnail') is-invalid @enderror" 
					placeholder="Enter a new avatar." />
				<span class="form-text text-muted">
					Jika thumbnail tidak ingin ditambahkan, kolom dapat dikosongkan.
				</span>
				<span class="form-text text-muted">
					Allowed File Extensions: .jpg, .jpeg, .png
				</span>
				<span class="form-text text-muted">
						For the best results on all devices, use an image that’s at least 480 x 360 pixels and 2MB or less.
					</span>
				@error('thumbnail')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div 
				class="form-group"
				id="showAbout">
				<label>About 
				<span class="text-danger">*</span></label>
				<textarea 
					class="form-control @error('about') is-invalid @enderror"
					rows="10" 
					name="about"
					id="about">{{old('about')}}</textarea>
				@error('about')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			
			<div class="form-group">
				<label>Privacy Setting 
				<span class="text-danger">*</span></label>
				<select 
					name="privacy_setting"
					class="form-control @error('privacy_setting') is-invalid @enderror">
					<option value="">--Pilih Privacy Setting--</option>
					<option value="public">Public</option>
					<option value="private">Private</option>
			     </select>
				@error('privacy_setting')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
		</div>
		<div class="card-footer">
			<button type="submit" class="btn btn-primary mr-2">Submit</button>
		</div>
	</form>

</div>

@endsection

@push('styles')
	<style>
		#showYoutube, #showUpload {
		     display: none;
		}
	</style>
@endpush

@push('scripts')
	<script>
		$(function() {
			$('#categories').select2({
				placeholder: "Pilih Kategori Video",
				allowClear: true,
			});

			$('#videoFor').select2({
				placeholder: "Pilih Pemilik Video",
				allowClear: true,
			});

			var e = document.getElementById("videoType");
			var selected = e.options[e.selectedIndex].value;

			if (selected === 'youtube') {
				$("#showYoutube").show();
				$("#pathYoutube").prop('disabled', false);

				$("#showTitle").hide();
				$("#showUpload").hide();
				$("#showThumbnail").hide();
				$("#showAbout").hide();
				$("#title").prop('disabled', true);
				$("#pathUpload").prop('disabled', true);
				$("#thumbnail").prop('disabled', true);
				$("#about").prop('disabled', true);

			} else if (selected === 'upload') {
				$("#showYoutube").hide();
				$("#pathYoutube").prop('disabled', true);

				$("#showTitle").show();
				$("#showUpload").show();
				$("#showThumbnail").show();
				$("#showAbout").show();
				$("#title").prop('disabled', false);
				$("#pathUpload").prop('disabled', false);
				$("#thumbnail").prop('disabled', false);
				$("#about").prop('disabled', false);

			} else {
				$("#showYoutube").hide();
				$("#pathYoutube").prop('disabled', true);
				
				$("#showTitle").hide();
				$("#showUpload").hide();
				$("#showThumbnail").hide();
				$("#showAbout").hide();
				$("#title").prop('disabled', true);
				$("#pathUpload").prop('disabled', true);
				$("#thumbnail").prop('disabled', false);
				$("#about").prop('disabled', true);
			}
			

			$("#videoType").on("change", function() {
				var valueInput = $(this).val();
				
				if (valueInput === 'youtube') {
					$("#showYoutube").show();
					$("#pathYoutube").prop('disabled', false);

					$("#showTitle").hide();
					$("#showUpload").hide();
					$("#showThumbnail").hide();
					$("#showAbout").hide();
					$("#title").prop('disabled', true);
					$("#pathUpload").prop('disabled', true);
					$("#thumbnail").prop('disabled', true);
					$("#about").prop('disabled', true);

				} else if (valueInput === 'upload') {
					$("#showYoutube").hide();
					$("#pathYoutube").prop('disabled', true);

					$("#showTitle").show();
					$("#showUpload").show();
					$("#showThumbnail").show();
					$("#showAbout").show();
					$("#title").prop('disabled', false);
					$("#pathUpload").prop('disabled', false);
					$("#thumbnail").prop('disabled', false);
					$("#about").prop('disabled', false);

				} else {
					$("#showYoutube").hide();
					$("#pathYoutube").prop('disabled', true);
					
					$("#showTitle").hide();
					$("#showUpload").hide();
					$("#showThumbnail").hide();
					$("#showAbout").hide();
					$("#title").prop('disabled', true);
					$("#pathUpload").prop('disabled', true);
					$("#thumbnail").prop('disabled', false);
					$("#about").prop('disabled', true);
					
				}
			
			});
		});
	</script>
@endpush

resources/views/admin/video/show.blade.php
<table class="table table-bordered">
	<tr>
		<th width="30%">Title</th>
		<td>{{ $video->title }}</td>
	</tr>
	<tr>
		<th width="30%">Thumbnail</th>
		<td>
			@if(!empty($video->thumbnail))
				@if($video->thumbnail && file_exists(storage_path('app/public/video_thumbnail/'.$video->thumbnail)))
					<img src="{{$video->getImage()}}" height="90" width="120">
				@elseif($video->thumbnail)
					<img src="{{$video->getImage()}}" height="90" width="120">
				@else
					<img src="https://via.placeholder.com/96x96" width="96px">
				@endif
			@else
				<img src="https://via.placeholder.com/180x320" height="90" width="120">
			@endif
		</td>
	</tr>
	<tr>
		<th width="30%">Kategori</th>
		<td>
			@if($video->categories->isNotEmpty())
				@foreach($video->categories as $categories)
					<span class="label label-inline label-light-primary font-weight-bold">
	                    {{ $categories->name }}
	                </span>
				@endforeach
			@else
			-
			@endif
		</td>
	</tr>
	<tr>
		<th width="30%">Tags</th>
		<td>
			@foreach($video->tagVideos as $tags)
				{{$tags->tag}}
			@endforeach
		</td>
	</tr>
	<tr>
		<th width="30%">Video Type</th>
		<td>
			@if( $video->privacy_setting === 'youtube')
				Youtube
			@else
				Upload
			@endif
		</td>
	</tr>
	<tr>
		<th width="30%">About</th>
		<td>
		@if($video->about === null )
			-
		@else
			{{ $video->about }}
		@endif
		</td>
	</tr>
	<tr>
		<th width="30%">Privacy Setting</th>
		<td>
			@if( $video->privacy_setting === 'public')
				Public
			@else
				Private
			@endif
		</td>
	</tr>
	<tr>
		<th width="30%">Views</th>
		<td>
			{{ $video->views_count }} <i class="fa fa-eye"></i>
		</td>
	</tr>
	<tr>
		<th width="30%">Likes</th>
		<td>
			{{ $video->countLike() }} <i class="far fa-thumbs-up"></i>
		</td>
	</tr>
	<tr>
		<th width="30%">Dislikes</th>
		<td>
			{{ $video->countDislike() }} <i class="far fa-thumbs-down"></i>
		</td>
	</tr>
	<tr>
		<th width="30%">Uploaded at</th>
		<td>{{ $video->created_at->diffForhumans()}}</td>
	</tr>
	<tr>
		<th width="30%">Owner</th>
		<td>
			<table class="table table-bordered w-100">
				<tr>
					<th>Nama</th>
					<th>Email</th>
				</tr>
				<tr>
					<td>{{ $video->createBy->name }}</td>
					<td>{{ $video->createBy->email }}</td>
				</tr>
			</table>
		</td>
	</tr>

	<tr>
		<th width="30%">Comments</th>
		@if($video->videoCommentParents->count())
			<td>
				<div class="accordion" id="accordionExample">
				  <div class="card">
				    <div class="card-header" id="headingOne">
				      <h2 class="mb-0">
				        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
				          Show Comments
				        </button>
				      </h2>
				    </div>

				    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
				      <div class="card-body">
				       	<table class="table table-bordered w-100">
							@php
								$rowspan = 0;
							@endphp

						 	@foreach($video->videoCommentParents as $comment)
						 		@php
						 			$rowspan = $comment->parents->count();
						 			$rowspan+=1;
						 		@endphp

								<tr> 
									<th width="75%" colspan="3">{{ $comment->content}} </th> 
									<th width="25%" rowspan="{{ $rowspan }}">
										<a 
											href="{{route('admin.comments.edit', $comment->id)}}" 
											class="btn btn-warning"
											title="edit">
											<i class="fa fa-edit"></i>
										</a>

										<form 
											class="d-inline" 
											action="{{route('admin.comments.destroy', $comment->id)}}" 
											method="POST">

											@csrf
											@method('delete')

											<button 
												class="btn btn-danger"
												title="delete">
												<i class="fa fa-trash"></i>
											</button>
										</form>
									</th> 
								</tr>
								@foreach( $comment->parents as $reply) 
									<tr> 
										<td width="50%" colspan="2">{{ $reply->content }}</td> 
										<td>
											<a 
												href="{{route('admin.comments.edit', $reply->id)}}" 
												class="btn btn-warning"
												title="edit">
												<i class="fa fa-edit"></i>
											</a>

											<form 
												class="d-inline" 
												action="{{route('admin.comments.destroy', $reply->id)}}" 
												method="POST">

												@csrf
												@method('delete')

												<button 
													class="btn btn-danger"
													title="delete">
													<i class="fa fa-trash"></i>
												</button>
											</form>
										</td>  
									</tr>
								@endforeach
							@endforeach
						</table>
				      </div>
				    </div>
				  </div>
				</div>
			</td>
		@else
			<td> - </td>
		@endif
	</tr>
</table>