routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;


Route::get('/login', [Admin\Auth\LoginController::class, 'index'])
		->name('login.index');
Route::post('/login', [Admin\Auth\LoginController::class, 'login'])
		->name('login');
Route::get('/resend-verifyemail/{email}', [Admin\Auth\LoginController::class, 'resendVerifyEmail'])
		->name('resend-verifyemail');

Route::get('/password/email', [Admin\Auth\ForgotPasswordController::class, 'index'])
		->name('password.email.index');
Route::post('/password/email/send', [Admin\Auth\ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email.send');

Route::get('/password/reset/{token}', [Admin\Auth\ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('/password/reset', [Admin\Auth\ResetPasswordController::class, 'reset'])->name('password.reset.update');


Route::group(['middleware' => 'admin'], static function() {
	Route::get('/', function() {
		return redirect()->route('admin.dashboard.index');
	});
	
	Route::post('/logout', [Admin\Auth\LoginController::class, 'logout'])
		->name('logout');

	Route::get('/dashboard', [Admin\DashboardController::class, 'index'])
			->name('dashboard.index');

	Route::resource('/banner', Admin\BannerController::class)->except('show');
	Route::get('/data/banner', Admin\DataTable\BannerController::class)
			->name('banner.data');

	Route::resource('/category', Admin\CategoryController::class)->except('show');
	Route::get('/data/category', Admin\DataTable\CategoryController::class)
			->name('category.data');

	Route::resource('/comments', Admin\CommentController::class)->except('show', 'index');
	Route::delete('/comments/{id}/delete-reply', [Admin\CommentController::class, 'destroyReply'])
			->name('comments.destroyReply');
	Route::get('/data/comments', Admin\DataTable\CommentController::class)
			->name('comments.data');

	Route::get('/video/from-channel', [Admin\VideoController::class, 'createFromChannel'])
			->name('video.from-channel');
	Route::get('/video/video-from-channel', [Admin\VideoController::class, 'videoFromChannelIndex'])
			->name('video.video-from-channel.index');
	Route::post('/video/video-from-channel-check', [Admin\VideoController::class, 'videoFromChannel'])
			->name('video.video-from-channel');
	Route::post('/video/more-video-from-channel/', [Admin\VideoController::class, 'moreVideoFromChannel'])
			->name('video.more-video-from-channel');
	Route::post('/video/store-video-from-channel', [Admin\VideoController::class, 'storeVideoFromChannel'])
			->name('video.store-video-from-channel');

	Route::post('/video/search-video-from-channel', [Admin\VideoController::class, 'searchVideoFromChannel'])
			->name('video.search.video-from-channel');
	Route::get('/video/search-video-from-channel', [Admin\VideoController::class, 'searchVideoFromChannelIndex'])
			->name('video.search.video-from-channel.index');
	Route::post('/video/search-more-video-from-channel/', [Admin\VideoController::class, 'searchMoreVideoFromChannel'])
			->name('video.search.more-video-from-channel');
	// Route::post('/video/search-store-video-from-channel', [Admin\VideoController::class, 'searchStoreVideoFromChannel'])
	// 		->name('video.search.store-video-from-channel');


	Route::resource('/video', Admin\VideoController::class);
	Route::get('/data/video', Admin\DataTable\VideoController::class)
			->name('video.data');

	Route::resource('/playlist', Admin\PlaylistController::class);
	Route::get('/data/playlist', Admin\DataTable\PlaylistController::class)
			->name('playlist.data');

	Route::resource('/channel', Admin\ChannelController::class)->except('show');
	Route::get('/data/channel', Admin\DataTable\ChannelController::class)
			->name('channel.data');

	Route::resource('/users', Admin\UserController::class);
	Route::get('/data/users', Admin\DataTable\UserController::class)
			->name('users.data');

	Route::get('/profile', [Admin\ProfilController::class, 'index'])
			->name('profil.index');
	Route::get('/profile/edit', [Admin\ProfilController::class, 'edit'])
			->name('profil.edit');
	Route::put('/profile/{id}/update', [Admin\ProfilController::class, 'update'])
			->name('profil.update');
	Route::put('/profile/{id}/change-password', [Admin\ProfilController::class, 'changePassword'])
			->name('profil.changePassword');

	Route::resource('/admins', Admin\AdminController::class);
	Route::get('/data/admins', Admin\DataTable\AdminController::class)
			->name('admins.data'); 
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers;
use App\Http\Controllers\Customer;
use App\Http\Controllers\StorageController;

Route::get('/', [Controllers\WelcomeController::class, 'index'])->name('welcome');
Route::get('/login', [Controllers\Auth\LoginController::class, 'index'])->name('login');
Route::post('/login', [Controllers\Auth\LoginController::class, 'login']);
Route::post('/resend-verifyemail', [Controllers\Auth\LoginController::class, 'resendVerifyEmail']);

Route::get('/register', [Controllers\Auth\RegisterController::class, 'index'])->name('register');
Route::post('/register', [Controllers\Auth\RegisterController::class, 'store']);
Route::get('/email/confirmation/{email}', [Controllers\Auth\RegisterController::class, 'confirmEmail'])->name('confirm.email');

Route::get('/home', [Controllers\HomeController::class, 'index'])->name('home');

Route::get('/password/reset', [Controllers\Auth\ForgotPasswordController::class, 'showLinkRequestForm']);
Route::post('/password/email', [Controllers\Auth\ForgotPasswordController::class, 'postEmail']);

Route::get('/password/reset/{token}', [Controllers\Auth\ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('/password/reset', [Controllers\Auth\ResetPasswordController::class, 'reset']);

Route::get('/authorize/{social}', [Controllers\Auth\SocialAuthorizeController::class, 'redirectToProvider']);
Route::get('/authorize/{social}/callback', [Controllers\Auth\SocialAuthorizeController::class, 'handleProviderCallback']);

Route::resource('/category', Controllers\CategoryController::class)->only('index', 'show');
Route::get('/api/category', [Controllers\CategoryController::class, 'APIIndex']);


Route::group(['prefix' => 'customer'], static function () {
    Route::group(['middleware' => 'auth'], static function() {
        Route::post('/logout', [Controllers\Auth\LoginController::class, 'logout'])->name('logout');
        Route::get('/', [Customer\MyAccountController::class, 'index'])->name('customer.account');
        Route::get('/password', [Customer\PasswordController::class, 'index'])->name('customer.password');
        Route::post('/password', [Customer\PasswordController::class, 'store']);

        Route::get('/api/avatar', [Customer\AvatarController::class, 'APIAvatar']);
        Route::post('/avatar', [Customer\AvatarController::class, 'store']);

        Route::get('/video', [Customer\VideoController::class, 'index'])->name('customer.video');
        Route::get('/video/watch/{video:slug}', [Customer\VideoController::class, 'watch'])->name('customer.video.watch');
        Route::get('/video/{video:slug}', [Customer\VideoController::class, 'edit'])->name('customer.video.edit');
        Route::put('/video/{video:slug}/update', [Customer\VideoController::class, 'update'])->name('customer.video.update');
        Route::delete('/video/{video:id}/delete', [Customer\VideoController::class, 'destroy']);
        Route::post('/video', [Customer\VideoController::class, 'store']);

        Route::get('/channel', [Customer\ChannelController::class, 'index'])->name('customer.index.channel');
        Route::get('/channel/create', [Customer\ChannelController::class, 'create'])->name('customer.create.channel');
        Route::post('/channel', [Customer\ChannelController::class, 'store']);
        Route::get('/channel/{channel}/edit', [Customer\ChannelController::class, 'edit'])->name('customer.edit.channel');
        Route::put('/channel/{channel}/update', [Customer\ChannelController::class, 'update'])->name('customer.update.channel');

        Route::post('/like', [Customer\UserLikeVideoController::class, 'store']);
        Route::post('/comment', [Customer\UserVideoCommentController::class, 'storeNewComment']);
        Route::post('/comment/reply', [Customer\UserVideoCommentController::class, 'storeReplyComment']);
        Route::post('/like-comment', [Customer\UserVideoCommentController::class, 'storeResponsComment']);
        Route::post('/subscribe', [Customer\UserSubscribeController::class, 'store']);

        Route::get('/playlist', [Customer\UserPlaylistController::class, 'index'])->name('customer.playlist');
        Route::get('/api/playlist', [Customer\UserPlaylistController::class, 'APIIndex']);
        Route::post('/playlist', [Customer\UserPlaylistController::class, 'store']);
        Route::post('/playlist-video', [Customer\UserPlaylistController::class, 'storeVideoPlaylist']);
        Route::delete('/playlist/{playlist}/{video}/delete', [Customer\UserPlaylistController::class, 'destroy']);

        Route::get('/notifications', [Customer\UserNotificationController::class, 'getUnreadNotification']);
        Route::get('/notifications/mark-read-all', [Customer\UserNotificationController::class, 'markReadAllNotif']);
        Route::get('/notifications/{id}', [Customer\UserNotificationController::class, 'markReadNotif']);
        
    });
    
});


Route::get('/watch/{channel}/{video}', Controllers\VideoController::class)->name('video');
Route::get('/watch/{channel}', Controllers\ChannelController::class)->name('channel');
Route::get('/api/video/{video}', [Controllers\VideoCommentController::class, 'APIIndex']);
Route::post('/api/search/video', [Controllers\ChannelController::class, 'search']);


Route::get('/search', [Controllers\SearchController::class, 'index'])->name('search.index');
Route::get('/banner/{slug}', [Controllers\BannerController::class, 'show'])->name('banner.show');


Route::get('/retrieve-storage/{encryptedPath}', [StorageController::class, 'retrieve'])->name('storage.retrieve');

Route::get('/about', [Controllers\Footer\AboutController::class, 'index'])->name('footer.about.index');
Route::get('/about-use', [Controllers\Footer\AboutUsController::class, 'index'])->name('footer.about-use.index');
Route::get('/media-sosial', [Controllers\Footer\MediaSosialController::class, 'index'])->name('footer.media-sosial.index');
Route::get('/pusat-bantuan', [Controllers\Footer\PusatBantuanController::class, 'index'])->name('footer.pusat-bantuan.index');

resources/views/admin/admins/create.blade.php
@extends('layouts.admin.default')

@section('title', 'Create Admin')
@section('pageTitle', 'Create Admin')

@section('content')

@if(session('error'))
    <div class="alert alert-custom alert-danger fade show" role="alert">
        <div class="alert-icon"><i class="flaticon-warning"></i></div>
        <div class="alert-text">{{ session('error') }}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="ki ki-close"></i></span>
            </button>
        </div>
    </div>
@endif

<div class="card card-custom gutter-b example example-compact">
	<div class="card-header">
		<h3 class="card-title">Create a New Admin</h3>
	</div>

	<form 
		action="{{ route('admin.admins.store') }}" 
		method="POST"
		enctype="multipart/form-data">

		@csrf

		<div class="card-body">
			<div class="form-group">
				<label>Name 
				<span class="text-danger">*</span></label>
				<input 
					type="text"
					name="name" 
					class="form-control @error('name') is-invalid @enderror"
					value="{{old('name')}}" 
					placeholder="Enter a new admin. " />
				@error('name')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Email 
				<span class="text-danger">*</span></label>
				<input 
					type="text"
					name="email" 
					class="form-control @error('email') is-invalid @enderror"
					value="{{old('email')}}" 
					placeholder="Enter a new email. " />
				@error('email')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Avatar
				<input 
					type="file"
					name="avatar" 
					class="form-control @error('avatar') is-invalid @enderror" 
					placeholder="Enter a new avatar." />
				<span class="form-text text-muted">
					Jika tidak ingin menambahkan avatar, kolom dapat dikosongkan.
				</span>
				<span class="form-text text-muted">
					Allowed File Extensions: .jpg, .jpeg, .png
				</span>
				@error('avatar')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Password 
				<span class="text-danger">*</span></label>
				<input 
					type="password"
					name="password" 
					class="form-control @error('password') is-invalid @enderror"
					value="" 
					placeholder="Enter a new user. " />
				@error('password')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Konfirmasi Password 
				<span class="text-danger">*</span></label>
				<input 
					type="password"
					name="password_confirmation" 
					class="form-control @error('password_confirmation') is-invalid @enderror"
					value="" 
					placeholder="Enter a new user. " />
				@error('password_confirmation')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
		</div>
		<div class="card-footer">
			<button type="submit" class="btn btn-primary mr-2">Submit</button>
		</div>
	</form>

</div>

@endsection

resources/views/admin/admins/edit.blade.php
@extends('layouts.admin.default')

@section('title', 'Create Admin')
@section('pageTitle', 'Edit Admin')

@section('content')

<div class="card card-custom gutter-b example example-compact">
	<div class="card-header">
		<h3 class="card-title">Edit Admin</h3>
	</div>

	<form 
		action="{{ route('admin.admins.update', $admin->id) }}" 
		method="POST"
		enctype="multipart/form-data">

		@csrf
		@method('PUT')

		<div class="card-body">
			<div class="form-group">
				<label>Name 
				<span class="text-danger">*</span></label>
				<input 
					type="text"
					name="name" 
					class="form-control @error('name') is-invalid @enderror"
					value="{{old('name') ?? $admin->name}}" 
					placeholder="Enter a new user. " />
				@error('name')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Email 
				<span class="text-danger">*</span></label>
				<input 
					type="text"
					name="email" 
					class="form-control @error('email') is-invalid @enderror"
					value="{{old('email') ?? $admin->email }}" 
					placeholder="Enter a new email. " />
				@error('email')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Avatar</label><br>
				<small class="text-muted">Current image</small><br>
				@if(!empty($admin->admin_avatar->thumbnail))
					@if( $admin->admin_avatar->thumbnail && Storage::exists($admin->admin_avatar->thumbnail) )
						<img src="{{$admin->admin_avatar->getImage()}}" height="100" width="100">
					@else
						<img src="https://via.placeholder.com/96x96" width="96px">
					@endif
				@else
					<img src="https://via.placeholder.com/96x96" width="96px">
				@endif
				<br><br>

				<input 
					type="file"
					name="avatar" 
					class="form-control @error('avatar') is-invalid @enderror" 
					placeholder="Enter a new avatar." />
				<span class="form-text text-muted">
					Jika avatar tidak ingin dirubah, kolom dapat dikosongkan.
				</span>
				<span class="form-text text-muted">
					Allowed File Extensions: .jpg, .jpeg, .png
				</span>
				@error('avatar')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Password 
				<span class="text-danger">*</span></label>
				<input 
					type="password"
					name="password" 
					class="form-control @error('password') is-invalid @enderror"
					value="" 
					placeholder="Enter a new user. " />
				@error('password')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
			<div class="form-group">
				<label>Konfirmasi Password 
				<span class="text-danger">*</span></label>
				<input 
					type="password"
					name="password_confirmation" 
					class="form-control @error('password_confirmation') is-invalid @enderror"
					value="" 
					placeholder="Enter a new user. " />
				@error('password_confirmation')
					<span class="invalid-feedback">
						{{ $message }}
					</span>
				@enderror
			</div>
		</div>
		<div class="card-footer">
			<button type="submit" class="btn btn-primary mr-2">Submit</button>
		</div>
	</form>

</div>

@endsection

resources/views/admin/admins/index.blade.php
@extends('layouts.admin.default')

@section('title', 'Admins')
@section('pageTitle', 'Admins')

@section('content')

  @if(session('success'))
    <div class="alert alert-custom alert-primary fade show" role="alert">
        <div class="alert-icon"><i class="flaticon-warning"></i></div>
        <div class="alert-text">{{ session('success') }}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="ki ki-close"></i></span>
            </button>
        </div>
    </div>
  @endif

  <div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
      <div class="card-title">
        <h3 class="card-label">Data Admins 
      </div>
      <div class="card-toolbar">
        <a 
          href = "{{ route('admin.admins.create')}}"
          class="btn btn-primary font-weight-bolder">

          <span class="svg-icon svg-icon-md">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
              <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                <rect x="0" y="0" width="24" height="24" />
                <circle fill="#000000" cx="9" cy="15" r="6" />
                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
              </g>
            </svg>
          </span>
          New Record
        </a>
      </div>
    </div>
    <div class="card-body">
      <table 
        class="table table-bordered table-hover table-checkable mt-10" 
        id="adminsTable">
        <thead>
          <tr>
            <th width="5%">No.</th>
            <th width="75%">Name</th>
            <th width="30%">Actions</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
@endsection

@push('styles')
  <link href="{{asset('assets/admin/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
@endpush

@push('scripts')
  <script src="{{asset('assets/admin/plugins/custom/datatables/datatables.bundle.js')}}"></script>
  <script src="{{asset('assets/admin/js/pages/crud/datatables/basic/headers.js')}}"></script>
  <script src="{{asset('assets/admin/plugins/sweetalert2/sweetalert2.min.js') }}"></script>

  <script>
  $(function(){
    $('#adminsTable').DataTable({
        "processing" : true,
        "serverSide" : true,
        "responsive" : true,
        "autoWidth"  : true,
      ajax: '{{ route('admin.admins.data') }}',
      columns: [
          {data: 'DT_RowIndex', orderable: false, searchable: false},
          {data: 'name'},
          {data: 'action'}  
      ]
    });

    $('#adminsTable'). on('click', 'button#delete', function(e) {
                e.preventDefault();
                var id = $(this).data('id');
                
                Swal.fire({
                title: 'Kamu yakin hapus data ini?',
                text: "data tidak bisa dikembalikan",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Oke, hapus!',
                cancelButtonText: 'Batalkan'
                }).then((result) => {
                    if (result.value) {
                        
                        $.ajax({
                            type: "DELETE",
                            url: "admins/" + id,
                            data: {
                                "id" : id,
                                "_token" : "{{ csrf_token() }}"
                            },
                            success: function(data) {
                                Swal.fire(
                                    'Berhasil dihapus!',
                                    'Data kamu telah dihapus',
                                    'success'
                                )
                                location.reload(true);
                            }
                        })
                    }
                })
            });
  });

  </script>
@endpush

resources/views/admin/admins/show.blade.php
<table class="table table-bordered">
	<tr>
		<th>Name</th>
		<td>{{ $admin->name }}</td>
	</tr>
	<tr>
		<th>Email</th>
		<td>{{ $admin->email}}</td>
	</tr>
	<tr>
		<th>Joined</th>
		<td>{{ $admin->created_at->diffForhumans()}}</td>
	</tr>
</table>